### PR TITLE
Fix: info-list shows tracking version info

### PR DESCRIPTION
**Pull request by wkentaro**
```
% wstool info
workspace: /Users/ken/ws/ws_vcstools

 Localname  S  SCM  Version (Spec)                        UID  (Spec)                 URI  (Spec) [http(s)://...]
 ---------  -  ---- --------------                        -----------                 ---------------------------
 vcstools_1 V  git  fix_force (master)                    a0a5457bd192 (cf774a270811) github.com/vcstools/vcstools.git
 tips       VC git  test_branch < remote2/master (master) 9f5a83cafda3 (1492c2b33489)     (github.com/wkentaro/tips.git)


% wstool info tips
Localname:         tips
Path               /Users/ken/ws/ws_vcstools/tips
Status:            VC
SCM:               git
URI:               https://github.com/wkentaro/tips.git
Current URI:
Version (Spec):    test_branch < remote2/master (master)
Spec-Revision:     1492c2b334896375cae946756b8c70e59b724d39
Current-Revision:  9f5a83cafda3b415e77afa6589bbb69c4bb1efc6
Other Properties:  []
```

### CODE REVIEW

**Comment by wkentaro** [comment]
Mentioned at: https://github.com/vcstools/wstool/pull/38#issuecomment-125332941

**Comment by wkentaro** [comment]
The output
`Version (Spec):    test_branch < remote2/master (master)` is okay?

Or should I make split output like:

```
Version (Spec): test_branch (master)
Current-Tracking-Version: remote2/master
```

**Comment by tkruse** [comment]
Maybe 

```
Version: test_branch <  remote2/master
Version-Spec: master
```

**Comment by wkentaro** [comment]
I adopted Spec-Version and Current-Version for consistency with revision information.

```
Spec-Version:      master
Current-Version:   test_branch < remote2/master
Spec-Revision:     1492c2b334896375cae946756b8c70e59b724d39
Current-Revision:  9f5a83cafda3b415e77afa6589bbb69c4bb1efc6
```

**Comment by tkruse** [comment]
I think this is good

**Comment by tkruse** [comment]
merged

**Comment by tkruse** [comment]
also good refactoring for svn, I thought about doing that myself, but got distracted.

**Comment by wkentaro** [comment]
thanks.

**Pull request merged**
